### ISSUE TITLE
Add a WordPress Installation

### ISSUE THREAD

**Issue by thewebprincess** [wpaustralia/wpaustralia.org#12]
I'd like to be able to blog updates, add comments, particularly in view of there being more scope for WPAU support of various groups and events, being able to post updates seems useful. Let's install WordPress, get someone to tweak a useful theme to make it look like us and let's start really digging into what we can do with the LA support

**Comment by BronsonQuick** [comment]
I'll tackle getting a Chassis install script setup to handle this for local dev. I'll let you folks tackle the actually hosting side of things!

**Comment by BronsonQuick** [comment]
I did a quick first pass of this `curl -L https://git.io/vxWPG | sh` but it needs some tweaks and testing. I'll revisit it tomorrow arvo.

**Comment by thewebprincess** [comment]
Awesome, thanks!

**Comment by ntwb** [comment]
Thanks 🙏

Cheers,

Stephen Edgar
________________________________

**Comment by ntwb** [comment]
🤦‍♂️
—

Cheers,

Stephen Edgar
________________________________

**Comment by ntwb** [comment]
> `curl -L https://git.io/vxWPG | sh`

Works for me, looking at the site as I drink my coffee and eat some vegemite on toast everything appears to have spun up perfectly 👌

**Comment by BronsonQuick** [comment]
Winning!

**Comment by dd32** [comment]
Just a quick note that auto-deploy is now also enabled for this repo to the site.
