### ISSUE TITLE
Get WordPress Hosting

### ISSUE THREAD

**Issue by thewebprincess** [wpaustralia/wpaustralia.org#13]
Hosting Requirements

- [ ] Php Version - 7.2
- [ ] Git Integration

**Comment by thewebprincess** [comment]
@ntwb  I'm assigning this to you in the hope you can gather the minimum hosting requirements for us. Thanks

**Comment by dd32** [comment]
Email - $city@wpaustralia.org?
Subdomain support - $city.wpaustralia.org ?

It'd be good to have at least a few email forwards in place for it, even if only for administrative purposes. Things like `brisbane@` could be useful if forwarded to the local organisers.

**Comment by dd32** [comment]
If anyone else has anything to add here, now's a good time.

I'll be organising some hosting for this in the near future.

**Comment by dd32** [comment]
This has been fixed for quite some time :)
We moved wpaustralia.org to a donated Conetix account.

Through that we've got access to email forwards and subdomain support for Multisite.
